/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeEscuchamosRouteImport } from './routes/te-escuchamos'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MisPropiedadesRouteImport } from './routes/mis-propiedades'
import { Route as MensajesRouteImport } from './routes/mensajes'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadIdRouteImport } from './routes/propiedad.$id'

const TeEscuchamosRoute = TeEscuchamosRouteImport.update({
  id: '/te-escuchamos',
  path: '/te-escuchamos',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPropiedadesRoute = MisPropiedadesRouteImport.update({
  id: '/mis-propiedades',
  path: '/mis-propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajesRoute = MensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadIdRoute = PropiedadIdRouteImport.update({
  id: '/propiedad/$id',
  path: '/propiedad/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/mensajes': typeof MensajesRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/te-escuchamos': typeof TeEscuchamosRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/mensajes': typeof MensajesRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/te-escuchamos': typeof TeEscuchamosRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/mensajes': typeof MensajesRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/perfil': typeof PerfilRoute
  '/publicar': typeof PublicarRoute
  '/te-escuchamos': typeof TeEscuchamosRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historial'
    | '/mensajes'
    | '/mis-propiedades'
    | '/perfil'
    | '/publicar'
    | '/te-escuchamos'
    | '/propiedad/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historial'
    | '/mensajes'
    | '/mis-propiedades'
    | '/perfil'
    | '/publicar'
    | '/te-escuchamos'
    | '/propiedad/$id'
  id:
    | '__root__'
    | '/'
    | '/historial'
    | '/mensajes'
    | '/mis-propiedades'
    | '/perfil'
    | '/publicar'
    | '/te-escuchamos'
    | '/propiedad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistorialRoute: typeof HistorialRoute
  MensajesRoute: typeof MensajesRoute
  MisPropiedadesRoute: typeof MisPropiedadesRoute
  PerfilRoute: typeof PerfilRoute
  PublicarRoute: typeof PublicarRoute
  TeEscuchamosRoute: typeof TeEscuchamosRoute
  PropiedadIdRoute: typeof PropiedadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/te-escuchamos': {
      id: '/te-escuchamos'
      path: '/te-escuchamos'
      fullPath: '/te-escuchamos'
      preLoaderRoute: typeof TeEscuchamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-propiedades': {
      id: '/mis-propiedades'
      path: '/mis-propiedades'
      fullPath: '/mis-propiedades'
      preLoaderRoute: typeof MisPropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensajes': {
      id: '/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof MensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedad/$id': {
      id: '/propiedad/$id'
      path: '/propiedad/$id'
      fullPath: '/propiedad/$id'
      preLoaderRoute: typeof PropiedadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistorialRoute: HistorialRoute,
  MensajesRoute: MensajesRoute,
  MisPropiedadesRoute: MisPropiedadesRoute,
  PerfilRoute: PerfilRoute,
  PublicarRoute: PublicarRoute,
  TeEscuchamosRoute: TeEscuchamosRoute,
  PropiedadIdRoute: PropiedadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
