/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosYCondicionesRouteImport } from './routes/terminos-y-condiciones'
import { Route as TeEscuchamosRouteImport } from './routes/te-escuchamos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PublicarRouteImport } from './routes/publicar'
import { Route as PoliticaDePrivacidadRouteImport } from './routes/politica-de-privacidad'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MisPropiedadesRouteImport } from './routes/mis-propiedades'
import { Route as MensajesRouteImport } from './routes/mensajes'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadIdRouteImport } from './routes/propiedad.$id'

const TerminosYCondicionesRoute = TerminosYCondicionesRouteImport.update({
  id: '/terminos-y-condiciones',
  path: '/terminos-y-condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const TeEscuchamosRoute = TeEscuchamosRouteImport.update({
  id: '/te-escuchamos',
  path: '/te-escuchamos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicarRoute = PublicarRouteImport.update({
  id: '/publicar',
  path: '/publicar',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadRoute = PoliticaDePrivacidadRouteImport.update({
  id: '/politica-de-privacidad',
  path: '/politica-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPropiedadesRoute = MisPropiedadesRouteImport.update({
  id: '/mis-propiedades',
  path: '/mis-propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajesRoute = MensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadIdRoute = PropiedadIdRouteImport.update({
  id: '/propiedad/$id',
  path: '/propiedad/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/mensajes': typeof MensajesRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/publicar': typeof PublicarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/te-escuchamos': typeof TeEscuchamosRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/mensajes': typeof MensajesRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/publicar': typeof PublicarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/te-escuchamos': typeof TeEscuchamosRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historial': typeof HistorialRoute
  '/mensajes': typeof MensajesRoute
  '/mis-propiedades': typeof MisPropiedadesRoute
  '/perfil': typeof PerfilRoute
  '/politica-de-privacidad': typeof PoliticaDePrivacidadRoute
  '/publicar': typeof PublicarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/te-escuchamos': typeof TeEscuchamosRoute
  '/terminos-y-condiciones': typeof TerminosYCondicionesRoute
  '/propiedad/$id': typeof PropiedadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historial'
    | '/mensajes'
    | '/mis-propiedades'
    | '/perfil'
    | '/politica-de-privacidad'
    | '/publicar'
    | '/reset-password'
    | '/te-escuchamos'
    | '/terminos-y-condiciones'
    | '/propiedad/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historial'
    | '/mensajes'
    | '/mis-propiedades'
    | '/perfil'
    | '/politica-de-privacidad'
    | '/publicar'
    | '/reset-password'
    | '/te-escuchamos'
    | '/terminos-y-condiciones'
    | '/propiedad/$id'
  id:
    | '__root__'
    | '/'
    | '/historial'
    | '/mensajes'
    | '/mis-propiedades'
    | '/perfil'
    | '/politica-de-privacidad'
    | '/publicar'
    | '/reset-password'
    | '/te-escuchamos'
    | '/terminos-y-condiciones'
    | '/propiedad/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistorialRoute: typeof HistorialRoute
  MensajesRoute: typeof MensajesRoute
  MisPropiedadesRoute: typeof MisPropiedadesRoute
  PerfilRoute: typeof PerfilRoute
  PoliticaDePrivacidadRoute: typeof PoliticaDePrivacidadRoute
  PublicarRoute: typeof PublicarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TeEscuchamosRoute: typeof TeEscuchamosRoute
  TerminosYCondicionesRoute: typeof TerminosYCondicionesRoute
  PropiedadIdRoute: typeof PropiedadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos-y-condiciones': {
      id: '/terminos-y-condiciones'
      path: '/terminos-y-condiciones'
      fullPath: '/terminos-y-condiciones'
      preLoaderRoute: typeof TerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/te-escuchamos': {
      id: '/te-escuchamos'
      path: '/te-escuchamos'
      fullPath: '/te-escuchamos'
      preLoaderRoute: typeof TeEscuchamosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publicar': {
      id: '/publicar'
      path: '/publicar'
      fullPath: '/publicar'
      preLoaderRoute: typeof PublicarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidad': {
      id: '/politica-de-privacidad'
      path: '/politica-de-privacidad'
      fullPath: '/politica-de-privacidad'
      preLoaderRoute: typeof PoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-propiedades': {
      id: '/mis-propiedades'
      path: '/mis-propiedades'
      fullPath: '/mis-propiedades'
      preLoaderRoute: typeof MisPropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensajes': {
      id: '/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof MensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedad/$id': {
      id: '/propiedad/$id'
      path: '/propiedad/$id'
      fullPath: '/propiedad/$id'
      preLoaderRoute: typeof PropiedadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistorialRoute: HistorialRoute,
  MensajesRoute: MensajesRoute,
  MisPropiedadesRoute: MisPropiedadesRoute,
  PerfilRoute: PerfilRoute,
  PoliticaDePrivacidadRoute: PoliticaDePrivacidadRoute,
  PublicarRoute: PublicarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TeEscuchamosRoute: TeEscuchamosRoute,
  TerminosYCondicionesRoute: TerminosYCondicionesRoute,
  PropiedadIdRoute: PropiedadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
